<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2012 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Extension folder
 */
$GLOBALS['TL_LANG']['MOD']['pageswitch'] = array('Seitenwechsler');


/**
 * Front end modules
 */
$GLOBALS['TL_LANG']['FMD']['pageswitch']	= array('Seitenwechsler', 'Das Modul erstellt einen Link zu einer Geschwister-Seite');

